baseURL = "/"
languageCode = "en-us"
title = "Brandon L. Kramer, PhD"
description = "Brandon L. Kramer, PhD - Postdoctoral Research Associate, Biocomplexity Institute, University of Virginia"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    content = "/:year/:month/:day/"

[params]
    author = "Brandon Kramer"
    description = "Postdoctoral Research Associate, Biocomplexity Institute, University of Virginia"
    logo = "favicon/brandonlkramer-cropped.png"
    twitterAuthor = "@brandonlkramer"
    githubUsername = "brandonleekramer"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/" 
    name = "home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2

[[menu.main]]
    url = "/kramer-cv-0520.pdf"
    name = "cv"
    weight = 3

[[menu.main]]
    url = "/publications/"
    name = "publications"
    weight = 4

[[menu.main]]
    url = "/projects/"
    name = "projects"
    weight = 5
 
[[menu.main]]
    url = "/tags/"
    name = "tags"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:brandonleekramer@gmail.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/brandonleekramer/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/brandonlkramer/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/brandonlkramer/"
    name = "fab fa-linkedin"
    weight = 4

