baseURL = "/"
languageCode = "en-us"
title = "Brandon Kramer, Ph.D."
description = "Brandon Kramer, PhD"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]
#publishDir = "docs"
#relativeurls = true

[permalinks]
    content = "/:year/:month/:day/"

[params]
    author = "Brandon Kramer"
    description = "Blockchain Researcher"
    logo = "favicon/blk-cropped.png"
    twitterAuthor = "@brandonlkramer"
    githubUsername = "brandonleekramer"
    accent = "#581F87" # dark colors do best
    backgroundColor = "#FFFFFF"
    font = "Oxygen" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/Kramer_CV_1022.pdf"
    name = "CV"
    weight = 2

[[menu.main]]
    url = "/Kramer_Resume_UX_1121.pdf"
    name = "Resume"
    weight = 3

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 4

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 5
    
[[menu.main]]
    url = "/packages/"
    name = "Packages"
    weight = 6
    
[[menu.main]]
    url = "/teaching/"
    name = "Teaching"
    weight = 7

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:brandonleekramer@gmail.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/brandonleekramer/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/brandonlkramer/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/brandonlkramer/"
    name = "fab fa-linkedin"
    weight = 4


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
