---
output: html_document
---

**Brandon Kramer, PhD** (they/them/he/him) is currently a Postdoctoral Research Associate in the Social and Decision Analytics Division at the University of Virginia's Biocomplexity Institute and Initiative. Generally, Brandon’s research interests lie at the intersection of science, technology, politics, and health. While trained as a sociologist, Brandon incorporates aspects of computational social science, science & technology studies, and social neuroscience to examine social and economic inequalities. This work has been published in *Science, Technology & Human Values*, *BioSocieties*, *Annals of Behavioral Medicine*, and the *Annual Review of Nutrition*.

In their [dissertation project](/projects/racialization-in-testosterone-research) (completed at Rutgers University in Spring 2019), Brandon studied how testosterone has been used to racialize populations in biomedical research and the impact that this has on understanding health disparities. By integrating various computational and qualitative strategies, [Brandon traced how testosterone researchers advance misleading and dangerous claims about racial differences in health and behavior](https://link.springer.com/article/10.1057/s41292-020-00200-w), ultimately arguing that these discourses contribute to racially-specific healthcare practices that exacerbate prostate cancer disparities between white and black men. As part of this ongoing research, Brandon is developing a project that uses natural language processing, machine learning, and network analysis to study the diffusion of discrimination and bias in communication networks more broadly.

Currently, Brandon spends most of their time working on multidisciplinary team science projects. Since graduating, Brandon has worked on collaborative projects - both in and outside of UVA - that examine [international collaboration networks in open-source software development](/projects/oss/), [the political history of nutrition science](/projects/impacts-and-echoes/), [the rise of "diversity" in biomedical research](/projects/diversity/), [the use of machine learning to predict gentrification and emerging employment areas](https://dspg-young-scholars-program.github.io/dspg20fairfax/), and [a large-scale project on economic mobility](https://dspg.dev8.uvaits.virginia.edu/economic-mobility/community-insights). You can find links to this work in the [projects tab](/projects).



