---
output: html_document
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3, h4, h5 {
  text-align: center;
}
```

#### <ins>**Publications**</ins> 

Kramer, B.L. (2020). "The Molecularization of Race in Testosterone Research." [*BioSocieties.*](https://link.springer.com/article/10.1057/s41292-020-00200-w) [Impact Factor = 3.083] [[GitHub Repo](https://github.com/brandonleekramer/race-in-testosterone-research)] [[Project Abstract](/projects/race-in-testosterone-research/)]

Wotecki, C. E., Kramer, B. L., Lancaster, V. & Cohen, S. (2020). “Impacts and Echoes: The Lasting Influence of the White House Conference on Food, Nutrition and Health.” [*Annual Review of Nutrition.*](https://www.annualreviews.org/doi/abs/10.1146/annurev-nutr-121619-045319) [Impact Factor = 10.897] [[GitHub Repo](https://github.com/uva-bi-sdad/impacts-and-echoes)] [[Project Website](https://impacts-and-echoes.netlify.app/description/)] 

Carlin, L. & Kramer, B.L. (2020). “Hair, Hormones & Ghosts: How Race is Submerged in Polycystic Ovary Syndrome.” [*Science, Technology & Human Values.*](https://journals.sagepub.com/doi/abs/10.1177/0162243920908647) [Impact Factor = 3.160] [[Project Abstract](/projects/pcos/)]

Himmelstein, M.S., Kramer, B.L., & Springer, K.W. (2019). Stress in Strong Convictions: Precarious Manhood Beliefs Moderate Cortisol Reactivity to Masculinity Threats. [*Psychology of Men and Masculinity.*](https://psycnet.apa.org/record/2018-48728-001) [Impact Factor = 1.813] [[Project Abstract](/projects/masculinity-and-stress/)]

Kramer, B.L., Himmelstein, M.S., & Springer, K.W. (2017). Getting to the Heart of Masculinity Stressors: Masculinity Threats Induce Pronounced Vagal Withdrawal During a Speaking Task. [*Annals of Behavioral Medicine.*](https://academic.oup.com/abm/article-abstract/51/6/846/4648585) [Impact Factor = 3.118] [[Project Abstract](/projects/masculinity-and-stress/)]

<br>

#### <ins>**Peer-Reviewed Conference Proceedings**</ins>

Moradi-Jamei, B. Kramer, B.L., Santiago Calderón, J.B., & Korkmaz, G. “Community Formation and the Detection of GitHub Collaboration Networks.” *Proceedings of the 2021 IEEE/ACM International Conference on Advances in Social Networks Analysis and Mining.*

<br>

#### <ins>**Papers Under Review**</ins> 

Kramer, B. L. & Lee, C. “The Rise of Diversity and Population Terminology in Biomedical Research.” *Draft and [Project Website](https://riseofdiversity.netlify.app/) Available.*

Gitre, E., Kramer, B. L., Dawson, C., & Korkmaz, G. “Across the Color Line: Using Text Networks to Examine Black and White US Soldiers’ Views on Race and Segregation during World War II.” *Draft and [Project Website](https://dspg-young-scholars-program.github.io/dspg20amsoldier) Available.*

Pristavec. P., Kramer, B. L., & Goldstein, J. “Modeling Neighborhood Change to Mitigate Gentrification: A Case Study of Fairfax County, VA.” *Draft Available.*

Keller, S., Pristavec. P., Kramer, B. L., Montalvo, C., Shipp, S., Dorius, C., Lancaster, V., Lambur, M., Linehan, Van Selous, K., Stockham, M., Voss, M., & Saimun, H. “A Review of Data Underlying Community-Based Research.” *Draft Available.* 

Glenn, S., Greene, K., Ray A., Kramer, B. L., Lyons, R. & Hecht, M. “The Relationship Between Social Media Use and Substance Use: Results from a Study of REAL media.” *Draft Available.*

<br>

#### <ins>**Other Public-Facing Work**</ins>

Kramer, B. L., Santiago Calderón, J.B., & Korkmaz, G. “U.S.-International Collaborations in Open-Source Software: 2018.” (forthcoming) *Invention, Knowledge Transfer, and Innovation. Science and Engineering Indicators (2022).* Official Report Published by the National Center for Science and Engineering Statistics.

Santiago Calderón, J.B., Kramer, B. L., & Korkmaz, G. “Cumulative Contribution to U.S. Federal Departments and Agencies to Open-Source Software on GitHub: 2010-2019.” (forthcoming) *Invention, Knowledge Transfer, and Innovation. Science and Engineering Indicators (2022).* Official Report Published by the National Center for Science and Engineering Statistics.

Kramer, B. L., Lancaster, V., and Moltavo, C. (2020) ["Three-State Comparison: Virginia, Iowa, and Oregon."](https://uva-bi-sdad.github.io/three-state-comparison/) Contextual Report for [UVA Biocomplexity & Gates Foundation Economic Mobility Shiny App]((https://dspgtools.shinyapps.io/EM-Data-Infrastructure/))

Tobin, E., Cong, C., Halewicz, V., Neville, Q., Pristavec, T., Goldstein, J., Kramer, B. L., Shipp, S., Tobin, J. (2020) [“Creating CommunityScapes: Using Data Science to Inform Evidence-Based Health Policy.”](https://www.methodspace.com/creating-communityscapes-using-data-science-to-inform-evidence-based-health-policy/) MethodSpace. SAGE Publishing. 

Cong, C., Isch, C., Tobin, E., Korkmaz, G., Santiago Calderón, J. B., Schroeder, A. and Kramer, B. L. (2020) [“Open Source: The Future of Software Innovation.”](https://www.methodspace.com/open-source-the-future-of-software-innovation/) MethodSpace. SAGE Publishing. 
