---
output: html_document
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3, h4, h5 {
  text-align: center;
}
```

### <ins>**Mentoring & Teaching Experience**</ins> 

<br>

#### **Rutgers University - Department of Sociology**

Over the past five years, I have taught and mentored in a variety of contexts, but my experience is a bit unconventional from most social scientists. During my time at Rutgers University, I was an Instructor for the *Sociology of Medicine and Health Care* for two semesters (Spring-Fall 2017) as well as a teaching assistant for *Contemporary Sociological Theory* (Spring 2016) and *Introduction to Sociological Research Methods* (Fall 2016). For my first four years at Rutgers (2012-2016), I also acted as Lab Manager in a research lab where I co-mentored more than 20 undergraduate students - with more than half of those students moving on to postgraduate or medical school after working with us. During this time, I trained students how to carry out behavioral experiments and clean cardiovascular data. Below is a training series detailing these procedures (see video series).

<center>

[Sociology of Medicine and Healthcare (Fall 2017) Course Syllabus](/Kramer_SMHC2017_Syllabus.pdf)

[Health, Environment, and Relational Ties (HEART) Laboratory](https://sites.google.com/site/heartlabrutgers/)

Mindware Cardiovascular Data Cleaning Tutorial

[Part 1](https://www.youtube.com/watch?v=HYU3Fwaobl8) - [Part 2](https://www.youtube.com/watch?v=tAydZeGFleI&t=) - [Part 3](https://www.youtube.com/watch?v=S3RsVh-MClU) - [Part 4](https://www.youtube.com/watch?v=MlTpCBPImhE) - [Part 5](https://www.youtube.com/watch?v=UZ6yraMquVw) - [Part 6](https://www.youtube.com/watch?v=adFf04yDVEM) - [Part 7](https://www.youtube.com/watch?v=dz6InnkkrJ4)

</center>

<br>

#### **University of Virginia - Biocomplexity Institute**

Over the past two years (July 2019-Present), I've been working as a Postdoctoral Research Associate at the University of Virginia. In my division, we do not have teaching responsibilities during the academic year, but we do host a summer program called [Data Science for the Public Good](https://datascienceforthepublicgood.org/events/symposium2020) (DSPG). Over the past three summers, our team has trained nearly 100 undergraduate and graduate students how to use data science to address a range of social and political issues defined by local and federal stakeholders. I personally have worked on 7 different teams over the past few years - leading one each of the past two summers. Below are some examples of the work my teams have produced. 

<center>

[2021 Open Source Software Project (App)](https://statshero.shinyapps.io/dspg21oss/) [(GitHub Repository)](https://github.com/DSPG-Young-Scholars-Program/dspg21oss)

[2020 Open Source Software Project (Website)](https://dspg-young-scholars-program.github.io/dspg20oss/) [(GitHub Repository)](https://github.com/DSPG-Young-Scholars-Program/dspg20oss)

[2020 American Solider Project (Website)](https://dspg-young-scholars-program.github.io/dspg20amsoldier/?dspg) [(GitHub Repository)](https://dspg-young-scholars-program.github.io/dspg20amsoldier/?dspg)

[2020 Fairfax County Project (Website)](https://dspg-young-scholars-program.github.io/dspg20fairfax/) [(GitHub Repository)](https://github.com/DSPG-Young-Scholars-Program/dspg20fairfax)

[2020 Patrick County Project (App)](https://teja.shinyapps.io/patrickdash/) [(GitHub Repository)](https://github.com/DSPG-Young-Scholars-Program/dspg20patrick)

[2019 Open Source Software Project (SAGE Brief)](https://www.methodspace.com/open-source-the-future-of-software-innovation/) [(GitHub Repository)](https://github.com/uva-bi-sdad/oss)

[2019 Fairfax County Project (SAGE Brief)](https://www.methodspace.com/creating-communityscapes-using-data-science-to-inform-evidence-based-health-policy/) [(GitHub Repository)](https://github.com/uva-bi-sdad/dspg19fairfax)

</center>

<br>

#### **Research Resources**

<center>

[Using Web of Science Data for Social Network Analysis in Gephi](https://docs.google.com/document/d/1chzoK4gzS4IMBs3wj-0xNSxBoR1qdKi1jVqempU9BmI/edit?usp=sharing)

[Interactive Resources on the History of Racism in the USA](https://docs.google.com/spreadsheets/d/1itAkPqMUH059j-Lkd78xqZky947zlbgM9ZjdBkqUQw8/edit#gid=0)

[Word Embeddings in the Social Sciences ](https://docs.google.com/spreadsheets/d/1hpaagIMbw2DoJRhWiQEC6r1jr956bj2iZDNv3L7opYI/edit#gid=0)

[Open Source Software Literature](https://docs.google.com/spreadsheets/d/1xk1t6HQsnYijHUTHFqOzV3CePQa3HF-X7B6quoy0CUw/edit#gid=0)

</center>