---
title: "Molecularization at the Intersections"
description: "In my dissertation, I examined how biomedical researchers produce racialized claims about testosterone, prostate cancer, and health disparities in biomedical research."
date: 2019-05-19 
tags: ["sts","networks", "race", "health","qualitative","ethics"]
weight: 4
draft: false
output: html_document
--- 

**Kramer, B. L. (2019). Molecularization at the Intersections: Testosterone, Prostate Cancer and the Construction of Racial Difference (Doctoral dissertation, Rutgers University-School of Graduate Studies).**

Biomedical researchers have long argued that racial differences in testosterone can help explain why African American men have an elevated risk of developing prostate cancer compared to their white counterparts. Using insights from science & technology studies, critical race theory and social network analysis, this dissertation interrogates the linkages between race, testosterone and prostate cancer, showing how testosterone has become racialized in scientific research and the impact that this process has had on the construction of racial disparities in prostate cancer. 

In my first chapter, I conduct a content analysis of publications that evaluate population differences in testosterone. I find that, despite widespread claims that testosterone varies between racial groups, the literature provides scant evidence to support these assertions. In turn, I identify three mechanisms – ambiguity, absence and data recycling – to help explain how racial difference testing has contributed to preserving the cultural myth of testosterone as a molecular marker of racialized masculinity. 

In my second chapter, I critically examine claims that African American men suffer from prostate cancer at two to three times the rate of white men in the US. My analysis shows that racial disparities in prostate cancer between these two groups are largely explained by group differences in socioeconomic status. Still, biomedical researchers tend to molecularize these disparities by advancing claims that black men have more “aggressive biologies,” which are supposedly fueled by higher testosterone levels. This theory carries over to shape racially-specific screening practices and the distribution of various biomedical interventions between black and white men. 

Using a mixed method approach to examine patterns of scientific consensus, my final chapter looks at how scientists conceptualize the association between testosterone and prostate cancer and how this has changed over time. While high levels of testosterone were considered a robust indicator of prostate cancer risk for more than seven decades, experts now argue that clinically low levels of testosterone may, in fact, be a more accurate risk factor for diagnosing this disease. I argue that this shift has impacted black and white men in distinct ways, reinforcing racial inequalities in healthcare in the process. For example, the Endocrine Society’s clinical guidelines explicitly advise clinicians against prescribing testosterone replacement therapies to African American men because of their higher risk of prostate cancer. 

Drawing from the major findings in each chapter, I argue that these recommendations are predicated on three historical myths that are no longer supported by existing scientific evidence. As a result, I suggest that these guidelines need to be re-written to incorporate the best available evidence and to remove race as a basis for distributing these drugs. More generally, my work advocates for biomedical researchers to allocate more attention to the social and structural factors that perpetuate health disparities rather than reinforcing the molecularization of race in contemporary scientific research.