---
title: "Masculinity & Stress"
description: "In this collaborative project with Kristen Springer (Rutgers) and Mary Himmelstein (Kent State), we studied how masculinity threats affect cardiovascular stress responses, which may accumulate over the life course to contribute to men's relatively worse cardiometabolic health."
tags: ["gender", "health", "experiments", "social neuroscience"]
date: 2017-12-01
weight: 48
draft: false
output: html_document
---

**Kramer, B.L., Himmelstein, M.S., & Springer, K.W. (2017). Getting to the heart of masculinity stressors: Masculinity threats induce pronounced vagal withdrawal during a speaking task. [*Annals of Behavioral Medicine*](https://pubmed.ncbi.nlm.nih.gov/28401414/), 51(6), 846-855. (Impact Factor = 3.118).**

In this study, we use an experimental framework to fill three existing gaps in the masculinities and health literatures. First, we examine the impact of masculinity threats on cortisol reactivity to understand how hegemonic masculinity gets “under the skin” to affect men’s health. Second, we test two variations of a masculinity threat, which represents an important methodological advance to understand which type of threat is most stressful. Third, we examine whether precarious manhood beliefs (agreement with the idea that manhood is a fleeting state that can be lost) moderate physiological reactivity to masculinity threats, to understand who might be most vulnerable to health consequences of masculinity norms. We found that men who most strongly subscribe to precarious manhood beliefs exhibited reactivity to a dropping masculinity threat (initially high score that drops from a score of 80 to a score of 25 during the experimental manipulation), but not a low masculinity threat (score that remains at 25 during the experimental manipulation) or any control conditions. Our results suggest that men who most strongly subscribe to precarious manhood beliefs may be most at risk for health problems associated with stress after a loss of masculinity status, rather than individuals with consistently low masculinity status.

<br>

**Himmelstein, M. S., Kramer, B. L., & Springer, K. W. (2019). Stress in strong convictions: Precarious manhood beliefs moderate cortisol reactivity to masculinity threats. [*Psychology of Men & Masculinities*](https://psycnet.apa.org/fulltext/2018-48728-001.html), 20(4), 491–502. (Impact Factor = 1.813)**

In this study, we use an experimental framework to fill three existing gaps in the masculinities and health literatures. First, we examine the impact of masculinity threats on cortisol reactivity to understand how hegemonic masculinity gets “under the skin” to affect men’s health. Second, we test two variations of a masculinity threat, which represents an important methodological advance to understand which type of threat is most stressful. Third, we examine whether precarious manhood beliefs (agreement with the idea that manhood is a fleeting state that can be lost) moderate physiological reactivity to masculinity threats, to understand who might be most vulnerable to health consequences of masculinity norms. We found that men who most strongly subscribe to precarious manhood beliefs exhibited reactivity to a dropping masculinity threat (initially high score that drops from a score of 80 to a score of 25 during the experimental manipulation), but not a low masculinity threat (score that remains at 25 during the experimental manipulation) or any control conditions. Our results suggest that men who most strongly subscribe to precarious manhood beliefs may be most at risk for health problems associated with stress after a loss of masculinity status, rather than individuals with consistently low masculinity status.