---
title: "Hair, Hormones, and Haunting"
description: "In this collaborative paper with Liz Carlin (CUNY), we examine how polycystic ovary syndrome is racialized in biomedical research."
date: 2020-02-24 
tags: ["sts", "race", "gender", "health", "qualitative","ethics"]
weight: 5
draft: false
output: html_document
---

**Carlin, L. & Kramer, B.L. (2020). “Hair, Hormones & Ghosts: How Race is Submerged in Polycystic Ovary Syndrome.” [*Science, Technology & Human Values.*](https://journals.sagepub.com/eprint/26AYSRJBPETS4ZA5ZDTS/full) (Impact Factor = 3.160).**

In this paper, we examine how polycystic ovary syndrome (PCOS) is racialized in biomedical research. Drawing from Star’s seminal concept of triangulation, we analyze how the diagnostic criteria for PCOS combine two different biomarkers: body hair and testosterone. Hair and hormones are both haunted by their use in eugenic research, and as clinical measures, they can carry forward powerful narratives of biological difference. PCOS researchers circulate strong claims about racial difference in hirsutism (“male-pattern” hair growth in women) as if they were established knowledge, sometimes calling for race-specific diagnostic thresholds. Tracing the links between (1) race and hirsutism, (2) hirsutism and testosterone, and (3) testosterone and race, we find that these connections are all conceptualized in ambiguous and inconsistent ways. Through triangulation, the uncertainty clouding each link is mitigated by the apparent strength of the chain as a whole. The logic linking race to disease is attenuated, allowing race to persist as a ghost variable. As PCOS is increasingly reframed as a risk factor for other conditions, racial stratification is submerged, implicit but actionable, at every stage of the life course cascade of risk.