---
title: "American Soldier"
author: "Brandon L. Kramer"
date: "8/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

“Across the Color Line” is part of a larger digital project entitled “The American Soldier in World War II.” The project is making accessible sixty-five thousand pages of uncensored handwritten commentaries composed by US servicemembers, along with quantitative datasets produced by a novel interdisciplinary US Army research branch. This small organization of leading psychologists and social scientists was tasked with analyzing and reporting on soldier morale, including the rank-and-file effects of segregation and relations between the races. This article showcases initial findings derived from a cross-sectional survey of Black and White soldiers administered in March of 1943, only months before the commencing of race rebellions in Detroit, Los Angeles, Harlem, and elsewhere over the country’s maintenance of Jim Crow while the US and its allies were at war to save democracy. Text correlation networks reveal in striking visual detail the effects of segregation on the experiences, habits, and opinions of both White and Black US citizen-soldiers, individually and collectively. Network-based visualizations from this extraordinary, untapped dataset are particularly effective at revealing the inverted epistemology of American racism and of W.E.B. Du Bois’s popular portrayal of Black America’s “double consciousness,” or “twoness,” as this article shows.
